### ISSUE TITLE
I killed it.

### ISSUE THREAD

**Issue by rdebath** [thezero/bf-compiler#1]
This code ...

``` brainfuck
++++[>++++<-]>[>[++++++++>]+[<]>-]>>>>+.<<+.>>-.<.<----.>---.<<----.>>---.<---.
```

Did this ...

```
c$ time python3 readbf.py x.b
Traceback (most recent call last):
  File "readbf.py", line 33, in <module>
    source = cmp.compile("".join(lines))
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/compiler.py", line 40, in compile
    b2p.Brainfuck2Python(self.source);
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/b2p.py", line 60, in __init__
    self.chr()
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/b2p.py", line 133, in chr
    program.process(self)
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/tokens.py", line 688, in process
    Container.process(self, self)
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/tokens.py", line 174, in process
    transformed = token.transform(program)
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/tokens.py", line 787, in transform
    program.memory.isStaticValue(pos)
  File "/home/robert/etc/BrainFuck/bb/thezero-bf-compiler/src/tokens.py", line 1429, in isStaticValue
    self.data[ptr] = 0
MemoryError

real    4m40.807s
user    4m38.924s
sys     0m1.744s
```

**Comment by thezero** [comment]
Well that was embarrasing :)

I revived it.

```
Jakub@CARROCK /c/web/bf-compiler/src$ python readbf.py github/i001.b
brainfuck
```
